FROM alpine:latest as build
LABEL maintainer="StatefulHQ <mail@stateful.com>"

RUN apk --no-cache add ca-certificates

RUN mkdir -p /opt/var/runme /opt/bin
COPY runme /opt/bin/runme
WORKDIR /opt/var/runme

ENTRYPOINT ["/opt/bin/runme"]
